#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="nhocgiftshop")]
public partial class nhocgiftshopdbDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertBaner(Baner instance);
  partial void UpdateBaner(Baner instance);
  partial void DeleteBaner(Baner instance);
  partial void InsertTuVan(TuVan instance);
  partial void UpdateTuVan(TuVan instance);
  partial void DeleteTuVan(TuVan instance);
  partial void InsertChiTietHoaDon(ChiTietHoaDon instance);
  partial void UpdateChiTietHoaDon(ChiTietHoaDon instance);
  partial void DeleteChiTietHoaDon(ChiTietHoaDon instance);
  partial void InsertDanhMuc(DanhMuc instance);
  partial void UpdateDanhMuc(DanhMuc instance);
  partial void DeleteDanhMuc(DanhMuc instance);
  partial void InsertDichVu(DichVu instance);
  partial void UpdateDichVu(DichVu instance);
  partial void DeleteDichVu(DichVu instance);
  partial void InsertGioiThieu(GioiThieu instance);
  partial void UpdateGioiThieu(GioiThieu instance);
  partial void DeleteGioiThieu(GioiThieu instance);
  partial void InsertHinhAnh(HinhAnh instance);
  partial void UpdateHinhAnh(HinhAnh instance);
  partial void DeleteHinhAnh(HinhAnh instance);
  partial void InsertHoaDon(HoaDon instance);
  partial void UpdateHoaDon(HoaDon instance);
  partial void DeleteHoaDon(HoaDon instance);
  partial void InsertKichCo(KichCo instance);
  partial void UpdateKichCo(KichCo instance);
  partial void DeleteKichCo(KichCo instance);
  partial void InsertKhachHang(KhachHang instance);
  partial void UpdateKhachHang(KhachHang instance);
  partial void DeleteKhachHang(KhachHang instance);
  partial void InsertKhuyenMai(KhuyenMai instance);
  partial void UpdateKhuyenMai(KhuyenMai instance);
  partial void DeleteKhuyenMai(KhuyenMai instance);
  partial void InsertSanPham(SanPham instance);
  partial void UpdateSanPham(SanPham instance);
  partial void DeleteSanPham(SanPham instance);
  #endregion
	
	public nhocgiftshopdbDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["nhocgiftshopConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public nhocgiftshopdbDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public nhocgiftshopdbDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public nhocgiftshopdbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public nhocgiftshopdbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Baner> Baners
	{
		get
		{
			return this.GetTable<Baner>();
		}
	}
	
	public System.Data.Linq.Table<TuVan> TuVans
	{
		get
		{
			return this.GetTable<TuVan>();
		}
	}
	
	public System.Data.Linq.Table<ChiTietHoaDon> ChiTietHoaDons
	{
		get
		{
			return this.GetTable<ChiTietHoaDon>();
		}
	}
	
	public System.Data.Linq.Table<DanhMuc> DanhMucs
	{
		get
		{
			return this.GetTable<DanhMuc>();
		}
	}
	
	public System.Data.Linq.Table<DichVu> DichVus
	{
		get
		{
			return this.GetTable<DichVu>();
		}
	}
	
	public System.Data.Linq.Table<GioiThieu> GioiThieus
	{
		get
		{
			return this.GetTable<GioiThieu>();
		}
	}
	
	public System.Data.Linq.Table<HinhAnh> HinhAnhs
	{
		get
		{
			return this.GetTable<HinhAnh>();
		}
	}
	
	public System.Data.Linq.Table<HoaDon> HoaDons
	{
		get
		{
			return this.GetTable<HoaDon>();
		}
	}
	
	public System.Data.Linq.Table<KichCo> KichCos
	{
		get
		{
			return this.GetTable<KichCo>();
		}
	}
	
	public System.Data.Linq.Table<KhachHang> KhachHangs
	{
		get
		{
			return this.GetTable<KhachHang>();
		}
	}
	
	public System.Data.Linq.Table<KhuyenMai> KhuyenMais
	{
		get
		{
			return this.GetTable<KhuyenMai>();
		}
	}
	
	public System.Data.Linq.Table<SanPham> SanPhams
	{
		get
		{
			return this.GetTable<SanPham>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Baner")]
public partial class Baner : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDBN;
	
	private string _TenBN;
	
	private string _HinhAnh;
	
	private System.Nullable<bool> _TrangThaiBN;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDBNChanging(int value);
    partial void OnIDBNChanged();
    partial void OnTenBNChanging(string value);
    partial void OnTenBNChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    partial void OnTrangThaiBNChanging(System.Nullable<bool> value);
    partial void OnTrangThaiBNChanged();
    #endregion
	
	public Baner()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDBN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDBN
	{
		get
		{
			return this._IDBN;
		}
		set
		{
			if ((this._IDBN != value))
			{
				this.OnIDBNChanging(value);
				this.SendPropertyChanging();
				this._IDBN = value;
				this.SendPropertyChanged("IDBN");
				this.OnIDBNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBN", DbType="NVarChar(100)")]
	public string TenBN
	{
		get
		{
			return this._TenBN;
		}
		set
		{
			if ((this._TenBN != value))
			{
				this.OnTenBNChanging(value);
				this.SendPropertyChanging();
				this._TenBN = value;
				this.SendPropertyChanged("TenBN");
				this.OnTenBNChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(200)")]
	public string HinhAnh
	{
		get
		{
			return this._HinhAnh;
		}
		set
		{
			if ((this._HinhAnh != value))
			{
				this.OnHinhAnhChanging(value);
				this.SendPropertyChanging();
				this._HinhAnh = value;
				this.SendPropertyChanged("HinhAnh");
				this.OnHinhAnhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiBN", DbType="Bit")]
	public System.Nullable<bool> TrangThaiBN
	{
		get
		{
			return this._TrangThaiBN;
		}
		set
		{
			if ((this._TrangThaiBN != value))
			{
				this.OnTrangThaiBNChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiBN = value;
				this.SendPropertyChanged("TrangThaiBN");
				this.OnTrangThaiBNChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TuVan")]
public partial class TuVan : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDTV;
	
	private string _TenTV;
	
	private System.Nullable<int> _IDTVC;
	
	private System.Nullable<bool> _TrangThaiTV;
	
	private EntitySet<TuVan> _TuVans;
	
	private EntitySet<SanPham> _SanPhams;
	
	private EntityRef<TuVan> _TuVan1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTVChanging(int value);
    partial void OnIDTVChanged();
    partial void OnTenTVChanging(string value);
    partial void OnTenTVChanged();
    partial void OnIDTVCChanging(System.Nullable<int> value);
    partial void OnIDTVCChanged();
    partial void OnTrangThaiTVChanging(System.Nullable<bool> value);
    partial void OnTrangThaiTVChanged();
    #endregion
	
	public TuVan()
	{
		this._TuVans = new EntitySet<TuVan>(new Action<TuVan>(this.attach_TuVans), new Action<TuVan>(this.detach_TuVans));
		this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
		this._TuVan1 = default(EntityRef<TuVan>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDTV
	{
		get
		{
			return this._IDTV;
		}
		set
		{
			if ((this._IDTV != value))
			{
				this.OnIDTVChanging(value);
				this.SendPropertyChanging();
				this._IDTV = value;
				this.SendPropertyChanged("IDTV");
				this.OnIDTVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTV", DbType="NVarChar(100)")]
	public string TenTV
	{
		get
		{
			return this._TenTV;
		}
		set
		{
			if ((this._TenTV != value))
			{
				this.OnTenTVChanging(value);
				this.SendPropertyChanging();
				this._TenTV = value;
				this.SendPropertyChanged("TenTV");
				this.OnTenTVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTVC", DbType="Int")]
	public System.Nullable<int> IDTVC
	{
		get
		{
			return this._IDTVC;
		}
		set
		{
			if ((this._IDTVC != value))
			{
				if (this._TuVan1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDTVCChanging(value);
				this.SendPropertyChanging();
				this._IDTVC = value;
				this.SendPropertyChanged("IDTVC");
				this.OnIDTVCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiTV", DbType="Bit")]
	public System.Nullable<bool> TrangThaiTV
	{
		get
		{
			return this._TrangThaiTV;
		}
		set
		{
			if ((this._TrangThaiTV != value))
			{
				this.OnTrangThaiTVChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiTV = value;
				this.SendPropertyChanged("TrangThaiTV");
				this.OnTrangThaiTVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuVan_TuVan", Storage="_TuVans", ThisKey="IDTV", OtherKey="IDTVC")]
	public EntitySet<TuVan> TuVans
	{
		get
		{
			return this._TuVans;
		}
		set
		{
			this._TuVans.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuVan_SanPham", Storage="_SanPhams", ThisKey="IDTV", OtherKey="IDTV")]
	public EntitySet<SanPham> SanPhams
	{
		get
		{
			return this._SanPhams;
		}
		set
		{
			this._SanPhams.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuVan_TuVan", Storage="_TuVan1", ThisKey="IDTVC", OtherKey="IDTV", IsForeignKey=true)]
	public TuVan TuVan1
	{
		get
		{
			return this._TuVan1.Entity;
		}
		set
		{
			TuVan previousValue = this._TuVan1.Entity;
			if (((previousValue != value) 
						|| (this._TuVan1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TuVan1.Entity = null;
					previousValue.TuVans.Remove(this);
				}
				this._TuVan1.Entity = value;
				if ((value != null))
				{
					value.TuVans.Add(this);
					this._IDTVC = value.IDTV;
				}
				else
				{
					this._IDTVC = default(Nullable<int>);
				}
				this.SendPropertyChanged("TuVan1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_TuVans(TuVan entity)
	{
		this.SendPropertyChanging();
		entity.TuVan1 = this;
	}
	
	private void detach_TuVans(TuVan entity)
	{
		this.SendPropertyChanging();
		entity.TuVan1 = null;
	}
	
	private void attach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.TuVan = this;
	}
	
	private void detach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.TuVan = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHoaDon")]
public partial class ChiTietHoaDon : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDCTHD;
	
	private System.Nullable<int> _IDHD;
	
	private System.Nullable<int> _IDSP;
	
	private System.Nullable<int> _IDKC;
	
	private System.Nullable<int> _Gia;
	
	private System.Nullable<int> _SoLuong;
	
	private EntityRef<HoaDon> _HoaDon;
	
	private EntityRef<KichCo> _KichCo;
	
	private EntityRef<SanPham> _SanPham;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCTHDChanging(int value);
    partial void OnIDCTHDChanged();
    partial void OnIDHDChanging(System.Nullable<int> value);
    partial void OnIDHDChanged();
    partial void OnIDSPChanging(System.Nullable<int> value);
    partial void OnIDSPChanged();
    partial void OnIDKCChanging(System.Nullable<int> value);
    partial void OnIDKCChanged();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnSoLuongChanging(System.Nullable<int> value);
    partial void OnSoLuongChanged();
    #endregion
	
	public ChiTietHoaDon()
	{
		this._HoaDon = default(EntityRef<HoaDon>);
		this._KichCo = default(EntityRef<KichCo>);
		this._SanPham = default(EntityRef<SanPham>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCTHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDCTHD
	{
		get
		{
			return this._IDCTHD;
		}
		set
		{
			if ((this._IDCTHD != value))
			{
				this.OnIDCTHDChanging(value);
				this.SendPropertyChanging();
				this._IDCTHD = value;
				this.SendPropertyChanged("IDCTHD");
				this.OnIDCTHDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHD", DbType="Int")]
	public System.Nullable<int> IDHD
	{
		get
		{
			return this._IDHD;
		}
		set
		{
			if ((this._IDHD != value))
			{
				if (this._HoaDon.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDHDChanging(value);
				this.SendPropertyChanging();
				this._IDHD = value;
				this.SendPropertyChanged("IDHD");
				this.OnIDHDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSP", DbType="Int")]
	public System.Nullable<int> IDSP
	{
		get
		{
			return this._IDSP;
		}
		set
		{
			if ((this._IDSP != value))
			{
				if (this._SanPham.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDSPChanging(value);
				this.SendPropertyChanging();
				this._IDSP = value;
				this.SendPropertyChanged("IDSP");
				this.OnIDSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKC", DbType="Int")]
	public System.Nullable<int> IDKC
	{
		get
		{
			return this._IDKC;
		}
		set
		{
			if ((this._IDKC != value))
			{
				if (this._KichCo.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDKCChanging(value);
				this.SendPropertyChanging();
				this._IDKC = value;
				this.SendPropertyChanged("IDKC");
				this.OnIDKCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
	public System.Nullable<int> Gia
	{
		get
		{
			return this._Gia;
		}
		set
		{
			if ((this._Gia != value))
			{
				this.OnGiaChanging(value);
				this.SendPropertyChanging();
				this._Gia = value;
				this.SendPropertyChanged("Gia");
				this.OnGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoLuong", DbType="Int")]
	public System.Nullable<int> SoLuong
	{
		get
		{
			return this._SoLuong;
		}
		set
		{
			if ((this._SoLuong != value))
			{
				this.OnSoLuongChanging(value);
				this.SendPropertyChanging();
				this._SoLuong = value;
				this.SendPropertyChanged("SoLuong");
				this.OnSoLuongChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_HoaDon", ThisKey="IDHD", OtherKey="IDHD", IsForeignKey=true)]
	public HoaDon HoaDon
	{
		get
		{
			return this._HoaDon.Entity;
		}
		set
		{
			HoaDon previousValue = this._HoaDon.Entity;
			if (((previousValue != value) 
						|| (this._HoaDon.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._HoaDon.Entity = null;
					previousValue.ChiTietHoaDons.Remove(this);
				}
				this._HoaDon.Entity = value;
				if ((value != null))
				{
					value.ChiTietHoaDons.Add(this);
					this._IDHD = value.IDHD;
				}
				else
				{
					this._IDHD = default(Nullable<int>);
				}
				this.SendPropertyChanged("HoaDon");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KichCo_ChiTietHoaDon", Storage="_KichCo", ThisKey="IDKC", OtherKey="IDKC", IsForeignKey=true)]
	public KichCo KichCo
	{
		get
		{
			return this._KichCo.Entity;
		}
		set
		{
			KichCo previousValue = this._KichCo.Entity;
			if (((previousValue != value) 
						|| (this._KichCo.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._KichCo.Entity = null;
					previousValue.ChiTietHoaDons.Remove(this);
				}
				this._KichCo.Entity = value;
				if ((value != null))
				{
					value.ChiTietHoaDons.Add(this);
					this._IDKC = value.IDKC;
				}
				else
				{
					this._IDKC = default(Nullable<int>);
				}
				this.SendPropertyChanged("KichCo");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietHoaDon", Storage="_SanPham", ThisKey="IDSP", OtherKey="IDSP", IsForeignKey=true)]
	public SanPham SanPham
	{
		get
		{
			return this._SanPham.Entity;
		}
		set
		{
			SanPham previousValue = this._SanPham.Entity;
			if (((previousValue != value) 
						|| (this._SanPham.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SanPham.Entity = null;
					previousValue.ChiTietHoaDons.Remove(this);
				}
				this._SanPham.Entity = value;
				if ((value != null))
				{
					value.ChiTietHoaDons.Add(this);
					this._IDSP = value.IDSP;
				}
				else
				{
					this._IDSP = default(Nullable<int>);
				}
				this.SendPropertyChanged("SanPham");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DanhMuc")]
public partial class DanhMuc : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDDM;
	
	private string _TenDM;
	
	private string _ChiTietDM;
	
	private System.Nullable<int> _IDDMC;
	
	private System.Nullable<bool> _TrangThaiDM;
	
	private EntitySet<DanhMuc> _DanhMucs;
	
	private EntitySet<SanPham> _SanPhams;
	
	private EntityRef<DanhMuc> _DanhMuc1;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDMChanging(int value);
    partial void OnIDDMChanged();
    partial void OnTenDMChanging(string value);
    partial void OnTenDMChanged();
    partial void OnChiTietDMChanging(string value);
    partial void OnChiTietDMChanged();
    partial void OnIDDMCChanging(System.Nullable<int> value);
    partial void OnIDDMCChanged();
    partial void OnTrangThaiDMChanging(System.Nullable<bool> value);
    partial void OnTrangThaiDMChanged();
    #endregion
	
	public DanhMuc()
	{
		this._DanhMucs = new EntitySet<DanhMuc>(new Action<DanhMuc>(this.attach_DanhMucs), new Action<DanhMuc>(this.detach_DanhMucs));
		this._SanPhams = new EntitySet<SanPham>(new Action<SanPham>(this.attach_SanPhams), new Action<SanPham>(this.detach_SanPhams));
		this._DanhMuc1 = default(EntityRef<DanhMuc>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDDM
	{
		get
		{
			return this._IDDM;
		}
		set
		{
			if ((this._IDDM != value))
			{
				this.OnIDDMChanging(value);
				this.SendPropertyChanging();
				this._IDDM = value;
				this.SendPropertyChanged("IDDM");
				this.OnIDDMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDM", DbType="NVarChar(100)")]
	public string TenDM
	{
		get
		{
			return this._TenDM;
		}
		set
		{
			if ((this._TenDM != value))
			{
				this.OnTenDMChanging(value);
				this.SendPropertyChanging();
				this._TenDM = value;
				this.SendPropertyChanged("TenDM");
				this.OnTenDMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTietDM", DbType="NVarChar(500)")]
	public string ChiTietDM
	{
		get
		{
			return this._ChiTietDM;
		}
		set
		{
			if ((this._ChiTietDM != value))
			{
				this.OnChiTietDMChanging(value);
				this.SendPropertyChanging();
				this._ChiTietDM = value;
				this.SendPropertyChanged("ChiTietDM");
				this.OnChiTietDMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDMC", DbType="Int")]
	public System.Nullable<int> IDDMC
	{
		get
		{
			return this._IDDMC;
		}
		set
		{
			if ((this._IDDMC != value))
			{
				if (this._DanhMuc1.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDDMCChanging(value);
				this.SendPropertyChanging();
				this._IDDMC = value;
				this.SendPropertyChanged("IDDMC");
				this.OnIDDMCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiDM", DbType="Bit")]
	public System.Nullable<bool> TrangThaiDM
	{
		get
		{
			return this._TrangThaiDM;
		}
		set
		{
			if ((this._TrangThaiDM != value))
			{
				this.OnTrangThaiDMChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiDM = value;
				this.SendPropertyChanged("TrangThaiDM");
				this.OnTrangThaiDMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_DanhMuc", Storage="_DanhMucs", ThisKey="IDDM", OtherKey="IDDMC")]
	public EntitySet<DanhMuc> DanhMucs
	{
		get
		{
			return this._DanhMucs;
		}
		set
		{
			this._DanhMucs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_SanPham", Storage="_SanPhams", ThisKey="IDDM", OtherKey="IDDM")]
	public EntitySet<SanPham> SanPhams
	{
		get
		{
			return this._SanPhams;
		}
		set
		{
			this._SanPhams.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_DanhMuc", Storage="_DanhMuc1", ThisKey="IDDMC", OtherKey="IDDM", IsForeignKey=true)]
	public DanhMuc DanhMuc1
	{
		get
		{
			return this._DanhMuc1.Entity;
		}
		set
		{
			DanhMuc previousValue = this._DanhMuc1.Entity;
			if (((previousValue != value) 
						|| (this._DanhMuc1.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._DanhMuc1.Entity = null;
					previousValue.DanhMucs.Remove(this);
				}
				this._DanhMuc1.Entity = value;
				if ((value != null))
				{
					value.DanhMucs.Add(this);
					this._IDDMC = value.IDDM;
				}
				else
				{
					this._IDDMC = default(Nullable<int>);
				}
				this.SendPropertyChanged("DanhMuc1");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_DanhMucs(DanhMuc entity)
	{
		this.SendPropertyChanging();
		entity.DanhMuc1 = this;
	}
	
	private void detach_DanhMucs(DanhMuc entity)
	{
		this.SendPropertyChanging();
		entity.DanhMuc1 = null;
	}
	
	private void attach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.DanhMuc = this;
	}
	
	private void detach_SanPhams(SanPham entity)
	{
		this.SendPropertyChanging();
		entity.DanhMuc = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDDV;
	
	private string _TenDV;
	
	private string _ChiTietDV;
	
	private System.Nullable<bool> _TrangThai;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDDVChanging(int value);
    partial void OnIDDVChanged();
    partial void OnTenDVChanging(string value);
    partial void OnTenDVChanged();
    partial void OnChiTietDVChanging(string value);
    partial void OnChiTietDVChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
	
	public DichVu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDDV
	{
		get
		{
			return this._IDDV;
		}
		set
		{
			if ((this._IDDV != value))
			{
				this.OnIDDVChanging(value);
				this.SendPropertyChanging();
				this._IDDV = value;
				this.SendPropertyChanged("IDDV");
				this.OnIDDVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenDV", DbType="NVarChar(100)")]
	public string TenDV
	{
		get
		{
			return this._TenDV;
		}
		set
		{
			if ((this._TenDV != value))
			{
				this.OnTenDVChanging(value);
				this.SendPropertyChanging();
				this._TenDV = value;
				this.SendPropertyChanged("TenDV");
				this.OnTenDVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTietDV", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string ChiTietDV
	{
		get
		{
			return this._ChiTietDV;
		}
		set
		{
			if ((this._ChiTietDV != value))
			{
				this.OnChiTietDVChanging(value);
				this.SendPropertyChanging();
				this._ChiTietDV = value;
				this.SendPropertyChanged("ChiTietDV");
				this.OnChiTietDVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
	public System.Nullable<bool> TrangThai
	{
		get
		{
			return this._TrangThai;
		}
		set
		{
			if ((this._TrangThai != value))
			{
				this.OnTrangThaiChanging(value);
				this.SendPropertyChanging();
				this._TrangThai = value;
				this.SendPropertyChanged("TrangThai");
				this.OnTrangThaiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GioiThieu")]
public partial class GioiThieu : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDGT;
	
	private string _TenGT;
	
	private string _ChiTietGT;
	
	private System.Nullable<bool> _TrangThaiGT;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDGTChanging(int value);
    partial void OnIDGTChanged();
    partial void OnTenGTChanging(string value);
    partial void OnTenGTChanged();
    partial void OnChiTietGTChanging(string value);
    partial void OnChiTietGTChanged();
    partial void OnTrangThaiGTChanging(System.Nullable<bool> value);
    partial void OnTrangThaiGTChanged();
    #endregion
	
	public GioiThieu()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDGT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDGT
	{
		get
		{
			return this._IDGT;
		}
		set
		{
			if ((this._IDGT != value))
			{
				this.OnIDGTChanging(value);
				this.SendPropertyChanging();
				this._IDGT = value;
				this.SendPropertyChanged("IDGT");
				this.OnIDGTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenGT", DbType="NVarChar(100)")]
	public string TenGT
	{
		get
		{
			return this._TenGT;
		}
		set
		{
			if ((this._TenGT != value))
			{
				this.OnTenGTChanging(value);
				this.SendPropertyChanging();
				this._TenGT = value;
				this.SendPropertyChanged("TenGT");
				this.OnTenGTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTietGT", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string ChiTietGT
	{
		get
		{
			return this._ChiTietGT;
		}
		set
		{
			if ((this._ChiTietGT != value))
			{
				this.OnChiTietGTChanging(value);
				this.SendPropertyChanging();
				this._ChiTietGT = value;
				this.SendPropertyChanged("ChiTietGT");
				this.OnChiTietGTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiGT", DbType="Bit")]
	public System.Nullable<bool> TrangThaiGT
	{
		get
		{
			return this._TrangThaiGT;
		}
		set
		{
			if ((this._TrangThaiGT != value))
			{
				this.OnTrangThaiGTChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiGT = value;
				this.SendPropertyChanged("TrangThaiGT");
				this.OnTrangThaiGTChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HinhAnh")]
public partial class HinhAnh : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDHA;
	
	private System.Nullable<int> _IDSP;
	
	private string _TenHA;
	
	private string _URL;
	
	private System.Nullable<bool> _TrangThaiHA;
	
	private EntityRef<SanPham> _SanPham;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHAChanging(int value);
    partial void OnIDHAChanged();
    partial void OnIDSPChanging(System.Nullable<int> value);
    partial void OnIDSPChanged();
    partial void OnTenHAChanging(string value);
    partial void OnTenHAChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnTrangThaiHAChanging(System.Nullable<bool> value);
    partial void OnTrangThaiHAChanged();
    #endregion
	
	public HinhAnh()
	{
		this._SanPham = default(EntityRef<SanPham>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHA", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDHA
	{
		get
		{
			return this._IDHA;
		}
		set
		{
			if ((this._IDHA != value))
			{
				this.OnIDHAChanging(value);
				this.SendPropertyChanging();
				this._IDHA = value;
				this.SendPropertyChanged("IDHA");
				this.OnIDHAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSP", DbType="Int")]
	public System.Nullable<int> IDSP
	{
		get
		{
			return this._IDSP;
		}
		set
		{
			if ((this._IDSP != value))
			{
				if (this._SanPham.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDSPChanging(value);
				this.SendPropertyChanging();
				this._IDSP = value;
				this.SendPropertyChanged("IDSP");
				this.OnIDSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenHA", DbType="NVarChar(100)")]
	public string TenHA
	{
		get
		{
			return this._TenHA;
		}
		set
		{
			if ((this._TenHA != value))
			{
				this.OnTenHAChanging(value);
				this.SendPropertyChanging();
				this._TenHA = value;
				this.SendPropertyChanged("TenHA");
				this.OnTenHAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(200)")]
	public string URL
	{
		get
		{
			return this._URL;
		}
		set
		{
			if ((this._URL != value))
			{
				this.OnURLChanging(value);
				this.SendPropertyChanging();
				this._URL = value;
				this.SendPropertyChanged("URL");
				this.OnURLChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiHA", DbType="Bit")]
	public System.Nullable<bool> TrangThaiHA
	{
		get
		{
			return this._TrangThaiHA;
		}
		set
		{
			if ((this._TrangThaiHA != value))
			{
				this.OnTrangThaiHAChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiHA = value;
				this.SendPropertyChanged("TrangThaiHA");
				this.OnTrangThaiHAChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_HinhAnh", Storage="_SanPham", ThisKey="IDSP", OtherKey="IDSP", IsForeignKey=true)]
	public SanPham SanPham
	{
		get
		{
			return this._SanPham.Entity;
		}
		set
		{
			SanPham previousValue = this._SanPham.Entity;
			if (((previousValue != value) 
						|| (this._SanPham.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SanPham.Entity = null;
					previousValue.HinhAnhs.Remove(this);
				}
				this._SanPham.Entity = value;
				if ((value != null))
				{
					value.HinhAnhs.Add(this);
					this._IDSP = value.IDSP;
				}
				else
				{
					this._IDSP = default(Nullable<int>);
				}
				this.SendPropertyChanged("SanPham");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDon")]
public partial class HoaDon : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDHD;
	
	private string _TenKH;
	
	private string _SDTKH;
	
	private string _Email;
	
	private string _DiaChi;
	
	private System.Nullable<bool> _TrangThaiHuy;
	
	private System.Nullable<bool> _TrangThaiMuaHang;
	
	private System.Nullable<char> _Code;
	
	private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHDChanging(int value);
    partial void OnIDHDChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnSDTKHChanging(string value);
    partial void OnSDTKHChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnTrangThaiHuyChanging(System.Nullable<bool> value);
    partial void OnTrangThaiHuyChanged();
    partial void OnTrangThaiMuaHangChanging(System.Nullable<bool> value);
    partial void OnTrangThaiMuaHangChanged();
    partial void OnCodeChanging(System.Nullable<char> value);
    partial void OnCodeChanged();
    #endregion
	
	public HoaDon()
	{
		this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHD", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDHD
	{
		get
		{
			return this._IDHD;
		}
		set
		{
			if ((this._IDHD != value))
			{
				this.OnIDHDChanging(value);
				this.SendPropertyChanging();
				this._IDHD = value;
				this.SendPropertyChanged("IDHD");
				this.OnIDHDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(100)")]
	public string TenKH
	{
		get
		{
			return this._TenKH;
		}
		set
		{
			if ((this._TenKH != value))
			{
				this.OnTenKHChanging(value);
				this.SendPropertyChanging();
				this._TenKH = value;
				this.SendPropertyChanged("TenKH");
				this.OnTenKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDTKH", DbType="NVarChar(20)")]
	public string SDTKH
	{
		get
		{
			return this._SDTKH;
		}
		set
		{
			if ((this._SDTKH != value))
			{
				this.OnSDTKHChanging(value);
				this.SendPropertyChanging();
				this._SDTKH = value;
				this.SendPropertyChanged("SDTKH");
				this.OnSDTKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiHuy", DbType="Bit")]
	public System.Nullable<bool> TrangThaiHuy
	{
		get
		{
			return this._TrangThaiHuy;
		}
		set
		{
			if ((this._TrangThaiHuy != value))
			{
				this.OnTrangThaiHuyChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiHuy = value;
				this.SendPropertyChanged("TrangThaiHuy");
				this.OnTrangThaiHuyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiMuaHang", DbType="Bit")]
	public System.Nullable<bool> TrangThaiMuaHang
	{
		get
		{
			return this._TrangThaiMuaHang;
		}
		set
		{
			if ((this._TrangThaiMuaHang != value))
			{
				this.OnTrangThaiMuaHangChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiMuaHang = value;
				this.SendPropertyChanged("TrangThaiMuaHang");
				this.OnTrangThaiMuaHangChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code", DbType="Char(1)")]
	public System.Nullable<char> Code
	{
		get
		{
			return this._Code;
		}
		set
		{
			if ((this._Code != value))
			{
				this.OnCodeChanging(value);
				this.SendPropertyChanging();
				this._Code = value;
				this.SendPropertyChanged("Code");
				this.OnCodeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDon_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="IDHD", OtherKey="IDHD")]
	public EntitySet<ChiTietHoaDon> ChiTietHoaDons
	{
		get
		{
			return this._ChiTietHoaDons;
		}
		set
		{
			this._ChiTietHoaDons.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
	{
		this.SendPropertyChanging();
		entity.HoaDon = this;
	}
	
	private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
	{
		this.SendPropertyChanging();
		entity.HoaDon = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KichCo")]
public partial class KichCo : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDKC;
	
	private System.Nullable<int> _IDSP;
	
	private string _KichCo1;
	
	private System.Nullable<int> _Gia;
	
	private string _DonVi;
	
	private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
	
	private EntityRef<SanPham> _SanPham;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKCChanging(int value);
    partial void OnIDKCChanged();
    partial void OnIDSPChanging(System.Nullable<int> value);
    partial void OnIDSPChanged();
    partial void OnKichCo1Changing(string value);
    partial void OnKichCo1Changed();
    partial void OnGiaChanging(System.Nullable<int> value);
    partial void OnGiaChanged();
    partial void OnDonViChanging(string value);
    partial void OnDonViChanged();
    #endregion
	
	public KichCo()
	{
		this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
		this._SanPham = default(EntityRef<SanPham>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKC", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDKC
	{
		get
		{
			return this._IDKC;
		}
		set
		{
			if ((this._IDKC != value))
			{
				this.OnIDKCChanging(value);
				this.SendPropertyChanging();
				this._IDKC = value;
				this.SendPropertyChanged("IDKC");
				this.OnIDKCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSP", DbType="Int")]
	public System.Nullable<int> IDSP
	{
		get
		{
			return this._IDSP;
		}
		set
		{
			if ((this._IDSP != value))
			{
				if (this._SanPham.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDSPChanging(value);
				this.SendPropertyChanging();
				this._IDSP = value;
				this.SendPropertyChanged("IDSP");
				this.OnIDSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="KichCo", Storage="_KichCo1", DbType="NVarChar(50)")]
	public string KichCo1
	{
		get
		{
			return this._KichCo1;
		}
		set
		{
			if ((this._KichCo1 != value))
			{
				this.OnKichCo1Changing(value);
				this.SendPropertyChanging();
				this._KichCo1 = value;
				this.SendPropertyChanged("KichCo1");
				this.OnKichCo1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Int")]
	public System.Nullable<int> Gia
	{
		get
		{
			return this._Gia;
		}
		set
		{
			if ((this._Gia != value))
			{
				this.OnGiaChanging(value);
				this.SendPropertyChanging();
				this._Gia = value;
				this.SendPropertyChanged("Gia");
				this.OnGiaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DonVi", DbType="NVarChar(20)")]
	public string DonVi
	{
		get
		{
			return this._DonVi;
		}
		set
		{
			if ((this._DonVi != value))
			{
				this.OnDonViChanging(value);
				this.SendPropertyChanging();
				this._DonVi = value;
				this.SendPropertyChanged("DonVi");
				this.OnDonViChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KichCo_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="IDKC", OtherKey="IDKC")]
	public EntitySet<ChiTietHoaDon> ChiTietHoaDons
	{
		get
		{
			return this._ChiTietHoaDons;
		}
		set
		{
			this._ChiTietHoaDons.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_KichCo", Storage="_SanPham", ThisKey="IDSP", OtherKey="IDSP", IsForeignKey=true)]
	public SanPham SanPham
	{
		get
		{
			return this._SanPham.Entity;
		}
		set
		{
			SanPham previousValue = this._SanPham.Entity;
			if (((previousValue != value) 
						|| (this._SanPham.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._SanPham.Entity = null;
					previousValue.KichCos.Remove(this);
				}
				this._SanPham.Entity = value;
				if ((value != null))
				{
					value.KichCos.Add(this);
					this._IDSP = value.IDSP;
				}
				else
				{
					this._IDSP = default(Nullable<int>);
				}
				this.SendPropertyChanged("SanPham");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
	{
		this.SendPropertyChanging();
		entity.KichCo = this;
	}
	
	private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
	{
		this.SendPropertyChanging();
		entity.KichCo = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhachHang")]
public partial class KhachHang : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDKH;
	
	private string _TenKH;
	
	private string _Email;
	
	private string _SDT;
	
	private string _DiaChi;
	
	private System.Nullable<System.DateTime> _NgaySinh;
	
	private System.Nullable<bool> _GioiTinh;
	
	private string _MatKhau;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKHChanging(int value);
    partial void OnIDKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSDTChanging(string value);
    partial void OnSDTChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    partial void OnGioiTinhChanging(System.Nullable<bool> value);
    partial void OnGioiTinhChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    #endregion
	
	public KhachHang()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDKH
	{
		get
		{
			return this._IDKH;
		}
		set
		{
			if ((this._IDKH != value))
			{
				this.OnIDKHChanging(value);
				this.SendPropertyChanging();
				this._IDKH = value;
				this.SendPropertyChanged("IDKH");
				this.OnIDKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(100)")]
	public string TenKH
	{
		get
		{
			return this._TenKH;
		}
		set
		{
			if ((this._TenKH != value))
			{
				this.OnTenKHChanging(value);
				this.SendPropertyChanging();
				this._TenKH = value;
				this.SendPropertyChanged("TenKH");
				this.OnTenKHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="NVarChar(20)")]
	public string SDT
	{
		get
		{
			return this._SDT;
		}
		set
		{
			if ((this._SDT != value))
			{
				this.OnSDTChanging(value);
				this.SendPropertyChanging();
				this._SDT = value;
				this.SendPropertyChanged("SDT");
				this.OnSDTChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(200)")]
	public string DiaChi
	{
		get
		{
			return this._DiaChi;
		}
		set
		{
			if ((this._DiaChi != value))
			{
				this.OnDiaChiChanging(value);
				this.SendPropertyChanging();
				this._DiaChi = value;
				this.SendPropertyChanged("DiaChi");
				this.OnDiaChiChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="Date")]
	public System.Nullable<System.DateTime> NgaySinh
	{
		get
		{
			return this._NgaySinh;
		}
		set
		{
			if ((this._NgaySinh != value))
			{
				this.OnNgaySinhChanging(value);
				this.SendPropertyChanging();
				this._NgaySinh = value;
				this.SendPropertyChanged("NgaySinh");
				this.OnNgaySinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioiTinh", DbType="Bit")]
	public System.Nullable<bool> GioiTinh
	{
		get
		{
			return this._GioiTinh;
		}
		set
		{
			if ((this._GioiTinh != value))
			{
				this.OnGioiTinhChanging(value);
				this.SendPropertyChanging();
				this._GioiTinh = value;
				this.SendPropertyChanged("GioiTinh");
				this.OnGioiTinhChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="NVarChar(100)")]
	public string MatKhau
	{
		get
		{
			return this._MatKhau;
		}
		set
		{
			if ((this._MatKhau != value))
			{
				this.OnMatKhauChanging(value);
				this.SendPropertyChanging();
				this._MatKhau = value;
				this.SendPropertyChanged("MatKhau");
				this.OnMatKhauChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KhuyenMai")]
public partial class KhuyenMai : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDKM;
	
	private string _TenKM;
	
	private string _ChiTietKM;
	
	private System.Nullable<System.DateTime> _NgayDangKM;
	
	private System.Nullable<System.DateTime> _NgayBDKM;
	
	private System.Nullable<System.DateTime> _NgayKTKM;
	
	private System.Nullable<bool> _TrangThaiKM;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKMChanging(int value);
    partial void OnIDKMChanged();
    partial void OnTenKMChanging(string value);
    partial void OnTenKMChanged();
    partial void OnChiTietKMChanging(string value);
    partial void OnChiTietKMChanged();
    partial void OnNgayDangKMChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangKMChanged();
    partial void OnNgayBDKMChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBDKMChanged();
    partial void OnNgayKTKMChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayKTKMChanged();
    partial void OnTrangThaiKMChanging(System.Nullable<bool> value);
    partial void OnTrangThaiKMChanged();
    #endregion
	
	public KhuyenMai()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDKM
	{
		get
		{
			return this._IDKM;
		}
		set
		{
			if ((this._IDKM != value))
			{
				this.OnIDKMChanging(value);
				this.SendPropertyChanging();
				this._IDKM = value;
				this.SendPropertyChanged("IDKM");
				this.OnIDKMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKM", DbType="NVarChar(100)")]
	public string TenKM
	{
		get
		{
			return this._TenKM;
		}
		set
		{
			if ((this._TenKM != value))
			{
				this.OnTenKMChanging(value);
				this.SendPropertyChanging();
				this._TenKM = value;
				this.SendPropertyChanged("TenKM");
				this.OnTenKMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTietKM", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string ChiTietKM
	{
		get
		{
			return this._ChiTietKM;
		}
		set
		{
			if ((this._ChiTietKM != value))
			{
				this.OnChiTietKMChanging(value);
				this.SendPropertyChanging();
				this._ChiTietKM = value;
				this.SendPropertyChanged("ChiTietKM");
				this.OnChiTietKMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangKM", DbType="Date")]
	public System.Nullable<System.DateTime> NgayDangKM
	{
		get
		{
			return this._NgayDangKM;
		}
		set
		{
			if ((this._NgayDangKM != value))
			{
				this.OnNgayDangKMChanging(value);
				this.SendPropertyChanging();
				this._NgayDangKM = value;
				this.SendPropertyChanged("NgayDangKM");
				this.OnNgayDangKMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBDKM", DbType="Date")]
	public System.Nullable<System.DateTime> NgayBDKM
	{
		get
		{
			return this._NgayBDKM;
		}
		set
		{
			if ((this._NgayBDKM != value))
			{
				this.OnNgayBDKMChanging(value);
				this.SendPropertyChanging();
				this._NgayBDKM = value;
				this.SendPropertyChanged("NgayBDKM");
				this.OnNgayBDKMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayKTKM", DbType="Date")]
	public System.Nullable<System.DateTime> NgayKTKM
	{
		get
		{
			return this._NgayKTKM;
		}
		set
		{
			if ((this._NgayKTKM != value))
			{
				this.OnNgayKTKMChanging(value);
				this.SendPropertyChanging();
				this._NgayKTKM = value;
				this.SendPropertyChanged("NgayKTKM");
				this.OnNgayKTKMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiKM", DbType="Bit")]
	public System.Nullable<bool> TrangThaiKM
	{
		get
		{
			return this._TrangThaiKM;
		}
		set
		{
			if ((this._TrangThaiKM != value))
			{
				this.OnTrangThaiKMChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiKM = value;
				this.SendPropertyChanged("TrangThaiKM");
				this.OnTrangThaiKMChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SanPham")]
public partial class SanPham : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDSP;
	
	private string _TenSP;
	
	private string _ChiTietSP;
	
	private System.Nullable<System.DateTime> _NgayDangSP;
	
	private System.Nullable<int> _LuotXem;
	
	private System.Nullable<bool> _TrangThaiSP;
	
	private System.Nullable<int> _IDDM;
	
	private System.Nullable<int> _IDTV;
	
	private EntitySet<ChiTietHoaDon> _ChiTietHoaDons;
	
	private EntitySet<HinhAnh> _HinhAnhs;
	
	private EntitySet<KichCo> _KichCos;
	
	private EntityRef<DanhMuc> _DanhMuc;
	
	private EntityRef<TuVan> _TuVan;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSPChanging(int value);
    partial void OnIDSPChanged();
    partial void OnTenSPChanging(string value);
    partial void OnTenSPChanged();
    partial void OnChiTietSPChanging(string value);
    partial void OnChiTietSPChanged();
    partial void OnNgayDangSPChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangSPChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnTrangThaiSPChanging(System.Nullable<bool> value);
    partial void OnTrangThaiSPChanged();
    partial void OnIDDMChanging(System.Nullable<int> value);
    partial void OnIDDMChanged();
    partial void OnIDTVChanging(System.Nullable<int> value);
    partial void OnIDTVChanged();
    #endregion
	
	public SanPham()
	{
		this._ChiTietHoaDons = new EntitySet<ChiTietHoaDon>(new Action<ChiTietHoaDon>(this.attach_ChiTietHoaDons), new Action<ChiTietHoaDon>(this.detach_ChiTietHoaDons));
		this._HinhAnhs = new EntitySet<HinhAnh>(new Action<HinhAnh>(this.attach_HinhAnhs), new Action<HinhAnh>(this.detach_HinhAnhs));
		this._KichCos = new EntitySet<KichCo>(new Action<KichCo>(this.attach_KichCos), new Action<KichCo>(this.detach_KichCos));
		this._DanhMuc = default(EntityRef<DanhMuc>);
		this._TuVan = default(EntityRef<TuVan>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDSP
	{
		get
		{
			return this._IDSP;
		}
		set
		{
			if ((this._IDSP != value))
			{
				this.OnIDSPChanging(value);
				this.SendPropertyChanging();
				this._IDSP = value;
				this.SendPropertyChanged("IDSP");
				this.OnIDSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenSP", DbType="NVarChar(100)")]
	public string TenSP
	{
		get
		{
			return this._TenSP;
		}
		set
		{
			if ((this._TenSP != value))
			{
				this.OnTenSPChanging(value);
				this.SendPropertyChanging();
				this._TenSP = value;
				this.SendPropertyChanged("TenSP");
				this.OnTenSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChiTietSP", DbType="NText", UpdateCheck=UpdateCheck.Never)]
	public string ChiTietSP
	{
		get
		{
			return this._ChiTietSP;
		}
		set
		{
			if ((this._ChiTietSP != value))
			{
				this.OnChiTietSPChanging(value);
				this.SendPropertyChanging();
				this._ChiTietSP = value;
				this.SendPropertyChanged("ChiTietSP");
				this.OnChiTietSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDangSP", DbType="Date")]
	public System.Nullable<System.DateTime> NgayDangSP
	{
		get
		{
			return this._NgayDangSP;
		}
		set
		{
			if ((this._NgayDangSP != value))
			{
				this.OnNgayDangSPChanging(value);
				this.SendPropertyChanging();
				this._NgayDangSP = value;
				this.SendPropertyChanged("NgayDangSP");
				this.OnNgayDangSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
	public System.Nullable<int> LuotXem
	{
		get
		{
			return this._LuotXem;
		}
		set
		{
			if ((this._LuotXem != value))
			{
				this.OnLuotXemChanging(value);
				this.SendPropertyChanging();
				this._LuotXem = value;
				this.SendPropertyChanged("LuotXem");
				this.OnLuotXemChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiSP", DbType="Bit")]
	public System.Nullable<bool> TrangThaiSP
	{
		get
		{
			return this._TrangThaiSP;
		}
		set
		{
			if ((this._TrangThaiSP != value))
			{
				this.OnTrangThaiSPChanging(value);
				this.SendPropertyChanging();
				this._TrangThaiSP = value;
				this.SendPropertyChanged("TrangThaiSP");
				this.OnTrangThaiSPChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDDM", DbType="Int")]
	public System.Nullable<int> IDDM
	{
		get
		{
			return this._IDDM;
		}
		set
		{
			if ((this._IDDM != value))
			{
				if (this._DanhMuc.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDDMChanging(value);
				this.SendPropertyChanging();
				this._IDDM = value;
				this.SendPropertyChanged("IDDM");
				this.OnIDDMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTV", DbType="Int")]
	public System.Nullable<int> IDTV
	{
		get
		{
			return this._IDTV;
		}
		set
		{
			if ((this._IDTV != value))
			{
				if (this._TuVan.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDTVChanging(value);
				this.SendPropertyChanging();
				this._IDTV = value;
				this.SendPropertyChanged("IDTV");
				this.OnIDTVChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_ChiTietHoaDon", Storage="_ChiTietHoaDons", ThisKey="IDSP", OtherKey="IDSP")]
	public EntitySet<ChiTietHoaDon> ChiTietHoaDons
	{
		get
		{
			return this._ChiTietHoaDons;
		}
		set
		{
			this._ChiTietHoaDons.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_HinhAnh", Storage="_HinhAnhs", ThisKey="IDSP", OtherKey="IDSP")]
	public EntitySet<HinhAnh> HinhAnhs
	{
		get
		{
			return this._HinhAnhs;
		}
		set
		{
			this._HinhAnhs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SanPham_KichCo", Storage="_KichCos", ThisKey="IDSP", OtherKey="IDSP")]
	public EntitySet<KichCo> KichCos
	{
		get
		{
			return this._KichCos;
		}
		set
		{
			this._KichCos.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DanhMuc_SanPham", Storage="_DanhMuc", ThisKey="IDDM", OtherKey="IDDM", IsForeignKey=true)]
	public DanhMuc DanhMuc
	{
		get
		{
			return this._DanhMuc.Entity;
		}
		set
		{
			DanhMuc previousValue = this._DanhMuc.Entity;
			if (((previousValue != value) 
						|| (this._DanhMuc.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._DanhMuc.Entity = null;
					previousValue.SanPhams.Remove(this);
				}
				this._DanhMuc.Entity = value;
				if ((value != null))
				{
					value.SanPhams.Add(this);
					this._IDDM = value.IDDM;
				}
				else
				{
					this._IDDM = default(Nullable<int>);
				}
				this.SendPropertyChanged("DanhMuc");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TuVan_SanPham", Storage="_TuVan", ThisKey="IDTV", OtherKey="IDTV", IsForeignKey=true)]
	public TuVan TuVan
	{
		get
		{
			return this._TuVan.Entity;
		}
		set
		{
			TuVan previousValue = this._TuVan.Entity;
			if (((previousValue != value) 
						|| (this._TuVan.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TuVan.Entity = null;
					previousValue.SanPhams.Remove(this);
				}
				this._TuVan.Entity = value;
				if ((value != null))
				{
					value.SanPhams.Add(this);
					this._IDTV = value.IDTV;
				}
				else
				{
					this._IDTV = default(Nullable<int>);
				}
				this.SendPropertyChanged("TuVan");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_ChiTietHoaDons(ChiTietHoaDon entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = this;
	}
	
	private void detach_ChiTietHoaDons(ChiTietHoaDon entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = null;
	}
	
	private void attach_HinhAnhs(HinhAnh entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = this;
	}
	
	private void detach_HinhAnhs(HinhAnh entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = null;
	}
	
	private void attach_KichCos(KichCo entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = this;
	}
	
	private void detach_KichCos(KichCo entity)
	{
		this.SendPropertyChanging();
		entity.SanPham = null;
	}
}
#pragma warning restore 1591
